proxmox_hostname: '{{ inventory_hostname }}'
proxmox_onboot: yes
proxmox_bridge: vmbr0
proxmox_firewall: no
proxmox_storage: local-zfs

proxmox_disk: 32 # GB
proxmox_memory: 4096 # MB
proxmox_cpu: host
proxmox_sockets: 1
proxmox_cores: 2
proxmox_bios: ovmf # 'ovmf' for UEFI, 'seabios' for BIOS

proxmox_template: rocky9.1
proxmox_password: '{{ root_password }}'
proxmox_pubkeys: '{{ root_authorized_keys }}'
proxmox_vlan: '{{ vlan.id }}'
proxmox_ip: '{{ ip }}'
proxmox_gateway: '{{ vlan.gateway }}'
proxmox_netmask: '{{ vlan.cidr | ansible.utils.ipaddr("prefix") }}'
proxmox_nameservers: '{{ vlan.dns_servers }}'
proxmox_searchdomain: '{{ domain }}'

proxmox_discard: yes
proxmox_ssd: yes

proxmox_kvm_vga: serial0
proxmox_kvm_ciuser: root
proxmox_kvm_scsihw: virtio-scsi-pci
proxmox_kvm_guest_agent: yes
proxmox_userdata: local:snippets/userdata.yaml
