apache_server_name: '{{ ansible_fqdn }}'
apache_server_aliases: '{{ [] if apache_letsencrypt else cnames }}'

apache_default_vhost: no
apache_autoindex: no

apache_letsencrypt: no
apache_use_ssl: yes
apache_use_http2: yes
apache_redirect_to_https: yes

apache_ldap_servers: '{{ freeipa_hosts }}'

apache_config: ''
