- name: restart saslauthd
  systemd:
    name: saslauthd
    state: restarted

- name: reload znc
  command: pkill -HUP znc
  failed_when: no

- name: restart znc
  systemd:
    name: znc
    state: restarted
