proxmox_repo_url: http://download.proxmox.com/debian/pve
proxmox_snippets_dir: /var/lib/vz/snippets
proxmox_kvm_image_dir: /usr/local/share/pve-kvm-images

proxmox_kvm_images:
  - name: rocky8.6
    url: https://download.rockylinux.org/pub/rocky/8/images/Rocky-8-GenericCloud-8.6.20220702.0.x86_64.qcow2
    sha256: 7b786a39eeb96e22dd85386377ff186737f6c1b9a5faa105b0a0a7a4895c29d0
    vmid: 9002

  - name: rocky8.7
    url: https://dl.rockylinux.org/pub/rocky/8/images/x86_64/Rocky-8-GenericCloud-Base-8.7-20221130.0.x86_64.qcow2
    sha256: 02e5a7564c979bca08e86e4f5bfbdad9bafcf4154844f7d2a029ec3f3df0fbd9
    vmid: 9004

  - name: rocky9.0
    url: https://download.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-9.0-20220830.0.x86_64.qcow2
    sha256: f02570e0ad3653df7f56baa8157739dbe92a003234acd5824dcf94d24694e20b
    vmid: 9003

  - name: rocky9.1
    url: https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base-9.1-20221130.0.x86_64.qcow2
    sha256: 4405926b4c84edf4a25a51d5ed36bffada04e5e143045c41c974a9a9d35937f1
    vmid: 9005

proxmox_nagios_user: nagios
proxmox_nagios_plugin_dir: /usr/lib/nagios/plugins
proxmox_nagios_home: /var/spool/nagios
proxmox_nagios_packages:
  - monitoring-plugins
  - snmpd

proxmox_nagios_sudo_whitelist:
  - /usr/bin/systemctl status -- *
