proxmox_repo_url: http://download.proxmox.com/debian/pve
proxmox_snippets_dir: /var/lib/vz/snippets
proxmox_kvm_image_dir: /usr/local/share/pve-kvm-images

proxmox_kvm_images:
  - name: rocky8.8
    url: https://dl.rockylinux.org/pub/rocky/8/images/x86_64/Rocky-8-GenericCloud-Base-8.8-20230518.0.x86_64.qcow2
    sha256: 086bf68f84c974cfcf533741c5be8752270df681a38f20423cf24b851d5edf77
    vmid: 9006

  - name: rocky9.2
    url: https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base-9.2-20230513.0.x86_64.qcow2
    sha256: 50510f98abe1b20a548102a05a9be83153b0bf634fc502d5c8d1f508f6de1430
    vmid: 9007

proxmox_nagios_user: nagios
proxmox_nagios_plugin_dir: /usr/lib/nagios/plugins
proxmox_nagios_home: /var/spool/nagios
proxmox_nagios_packages:
  - monitoring-plugins
  - snmpd

proxmox_nagios_sudo_whitelist:
  - /usr/bin/systemctl status -- *
