postfix_message_size_limit: 67108864  # 64 MB
postfix_recipient_delimiter: '+'
postfix_lmtp_require_tls: yes
postfix_virtual_domains: ['{{ email_domain }}']
postfix_myorigin: '{{ email_domain }}'
postfix_mynetworks: "{{ vlans.values() | map(attribute='cidr') }}"
postfix_myhostname: '{{ ansible_fqdn }}'

postfix_virtual_transport: lmtp:inet:{{ imap_host }}:24
postfix_mailbox_quota_service: inet:{{ imap_host }}:10993
postfix_milter: inet:{{ rspamd_host }}:11332

postfix_recipient_group: role-imap-access
