postfix_message_size_limit: 67108864  # 64 MB
postfix_recipient_delimiter: '+'
postfix_lmtp_require_tls: yes
postfix_virtual_domains: ['{{ email_domain }}']
postfix_myorigin: '{{ email_domain }}'
postfix_mynetworks: "{{ vlans.values() | map(attribute='cidr') }}"
postfix_myhostname: '{{ ansible_fqdn }}'

postfix_lmtp_host: '{{ imap_host }}'
postfix_lmtp_port: 24
postfix_quota_host: '{{ postfix_lmtp_host }}'
postfix_quota_port: 10993
postfix_rspamd_host: '{{ rspamd_host }}'
postfix_rspamd_port: 11332

postfix_recipient_group: role-imap-access
