asterisk_local_nets:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16

asterisk_timezone: '{{ timezone }}'
asterisk_locale: en_US.UTF-8

asterisk_public_fqdn: '{{ ansible_fqdn }}'
asterisk_from_domain: '{{ email_domain }}'

asterisk_rtp_port_start: 10000
asterisk_rtp_port_end: 10999
asterisk_sip_port: 5060
asterisk_sip_tls_port: 5061

asterisk_http_port: 8088
asterisk_https_port: 8089

asterisk_voicemail_formats:
  - wav49
  - gsm
  - wav

asterisk_mail_from: asterisk-noreply@{{ email_domain }}

asterisk_voicemail_email_subject: 'New voicemail ${VM_MSGNUM} in mailbox ${VM_MAILBOX}'
asterisk_voicemail_email_body: 'Hi ${VM_NAME},\n\nYou have a new voicemail in mailbox ${VM_MAILBOX}.\n\nFrom: ${VM_CALLERID}\nDate: ${VM_DATE}\nDuration: ${VM_DUR}\nMessage Number: ${VM_MSGNUM}'
asterisk_voicemail_email_date_format: '%A, %B %d, %Y at %r'
asterisk_voicemail_min_password: 4

asterisk_voicemail_max_message_count: 100
asterisk_voicemail_max_message_secs: 300
asterisk_voicemail_max_greeting_secs: 60
asterisk_voicemail_max_failed_logins: 3

asterisk_sip_trunks: []
asterisk_sip_extensions: []
asterisk_queues: []
asterisk_ari_users: []
asterisk_voicemail_contexts: {}
