mastodon_version: 4.1.4

mastodon_domain: '{{ email_domain }}'
mastodon_web_domain: '{{ ansible_fqdn }}'
mastodon_access_group: role-mastodon-access

mastodon_db_user: s-mastodon
mastodon_db_host: '{{ postgresql_host }}'
mastodon_db_name: mastodon

mastodon_ldap_host: '{{ freeipa_hosts | first }}'

mastodon_email_from: 'mastodon-noreply@{{ email_domain }}'

mastodon_default_locale: en

mastodon_registrations: close

mastodon_redis_port: 6379
mastodon_web_port: 8008
mastodon_streaming_port: 8009

mastodon_sysaccount_username: mastodon

mastodon_login_cidrs: []
