- name: generate chrony.conf
  template:
    src: etc/chrony/chrony.conf.j2
    dest: /etc/chrony/chrony.conf
  notify: restart chrony

- name: start chrony
  systemd:
    name: chronyd
    enabled: yes
    state: started
