apache_use_nfs: no
apache_can_network_relay: yes
apache_can_network_connect: no
apache_can_network_connect_db: no
apache_can_connect_ldap: no
apache_can_sendmail: no
apache_gssapi: no

apache_listen_ports:
  - 80

apache_ssl_listen_ports:
  - 443

apache_sysaccount_username: apache

apache_backup_dirs: []
