linux_desktop_packages:
  - '@fonts'
  - '@hardware-support'
  - '@internet-browser'
  - '@base-x'
  - '@networkmanager-submodules'
  - '@print-client'
  - evolution
  - libreoffice-calc
  - libreoffice-draw
  - libreoffice-impress
  - libreoffice-math
  - libreoffice-writer
  - ffmpeg-libs
  - ffmpeg
  - nfs4-acl-tools
  - hexchat
  - vlc
  - youtube-dl
  - gstreamer1-plugins-ugly
  - gstreamer1-plugins-bad-freeworld
  - gstreamer1-libav
  - gstreamer1-vaapi
  - libva-utils
  - intel-media-driver
  - seahorse
  - inkscape
  - libdvdcss
  - gimp
  - brasero
  - ntfs-3g
  - ntfsprogs
  - exfatprogs
  - chromium
  - audacious

  # xfce
  - '@Xfce'
  - ristretto
  - parole
  - mousepad
  - xfce4-weather-plugin
  - xfce4-taskmanager
  - xfce4-notifyd
  - xfce4-screenshooter
  - xfce4-whiskermenu-plugin

  # extra apps
  - engrampa
  - gnome-keyring
  - gnome-keyring-pam
  - evince
  - totem-video-thumbnailer

  # lightdm
  - lightdm
  - lightdm-gtk

  # qogir theme
  - gtk2-engines
  - gtk-murrine-engine

linux_desktop_excluded_packages:
  - gnome-software
  - libva-intel-driver

linux_desktop_hbac_hostgroup: linux_desktops

linux_desktop_flathub_repos:
  - name: flathub
    url: https://dl.flathub.org/repo/flathub.flatpakrepo

linux_desktop_flatpaks:
  - org.signal.Signal
  - com.bitwarden
  - org.libretro.RetroArch
  - ca.littlesvr.asunder
  - org.gnome.EasyTAG
  - com.makemkv.MakeMKV
  - org.gnucash.GnuCash
  - org.gnome.Rhythmbox3
  - org.gajim.Gajim
  - org.gajim.Gajim.Plugin.omemo

linux_desktop_flatpak_overrides:
  org.gnome.EasyTAG:    --filesystem=host
  org.gnome.Rhythmbox3: --filesystem=host
  org.signal.Signal:    --env=SIGNAL_USE_TRAY_ICON=1

linux_desktop_qogir_url: https://github.com/vinceliuice/Qogir-theme/archive/refs/tags/{{ linux_desktop_qogir_version }}.tar.gz
linux_desktop_qogir_icon_url: https://github.com/vinceliuice/Qogir-icon-theme/archive/refs/tags/{{ linux_desktop_qogir_icon_version }}.tar.gz
linux_desktop_qogir_source_dir: /usr/local/src/qogir
linux_desktop_qogir_icon_source_dir: /usr/local/src/qogir-icons
