linux_desktop_packages:
  - '@fonts'
  - '@hardware-support'
  - '@internet-browser'
  - '@base-x'
  - '@networkmanager-submodules'
  - '@print-client'
  - '@KDE Plasma Workspaces'
  - libreoffice-calc
  - libreoffice-draw
  - libreoffice-impress
  - libreoffice-math
  - libreoffice-writer
  - ffmpeg-libs
  - ffmpeg
  - nfs4-acl-tools
  - vlc
  - youtube-dl
  - gstreamer1-plugins-ugly
  - gstreamer1-plugins-bad-freeworld
  - gstreamer1-libav
  - gstreamer1-vaapi
  - libva-utils
  - intel-media-driver
  - inkscape
  - libdvdcss
  - gimp
  - ntfs-3g
  - ntfsprogs
  - exfatprogs
  - chromium
  - audacious


linux_desktop_excluded_packages:
  - libva-intel-driver

linux_desktop_hbac_hostgroup: linux_desktops

linux_desktop_flathub_repos:
  - name: flathub
    url: https://dl.flathub.org/repo/flathub.flatpakrepo

linux_desktop_flatpaks:
  - org.signal.Signal
  - com.bitwarden
  - org.libretro.RetroArch
  - ca.littlesvr.asunder
  - org.gnome.EasyTAG
  - com.makemkv.MakeMKV
  - org.gnucash.GnuCash
  - org.gajim.Gajim
  - org.gajim.Gajim.Plugin.omemo

linux_desktop_flatpak_overrides:
  org.gnome.EasyTAG:    --filesystem=host
  org.gnome.Rhythmbox3: --filesystem=host
  org.signal.Signal:    --env=SIGNAL_USE_TRAY_ICON=1
