- name: install gajim dependencies
  dnf:
    name:
      - gajim
      - python3-devel
    state: present

- name: install axolotl
  pip:
    name: python-axolotl
    state: present

- name: override gajim launch script
  copy:
    src: usr/local/bin/gajim
    dest: /usr/local/bin/gajim
    mode: 0555
