- name: generate gdm configuration
  template:
    src: etc/gdm/custom.conf.j2
    dest: /etc/gdm/custom.conf
  notify: restart gdm

- name: disable lightdm
  systemd:
    name: lightdm
    enabled: no
    state: stopped

- name: enable gdm
  systemd:
    name: gdm
    enabled: yes
    state: started
