- name: install packages
  dnf:
    name: '{{ linux_desktop_packages }}'
    exclude: '{{ linux_desktop_excluded_packages }}'
    state: present

- name: enable GuC for intel card
  copy:
    content: |
      options i915 enable_guc=2 enable_fbc=1
    dest: /etc/modprobe.d/i915.conf
  register: i915_options

- name: warn if reboot needed
  fail:
    msg: A reboot is needed to apply settings to i915 graphics module.
  when: i915_options.changed
  ignore_errors: yes

- name: set default target to graphical
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link

- name: generate sddm configuration
  copy:
    src: etc/sddm.conf
    dest: /etc/sddm.conf
  notify: restart sddm

- name: enable sddm
  systemd:
    name: sddm
    enabled: yes
    state: started

- name: add flathub flatpak repository
  flatpak_remote:
    name: '{{ item.name }}'
    flatpakrepo_url: '{{ item.url }}'
    state: present
  loop: '{{ linux_desktop_flathub_repos }}'

- name: install flatpak applications
  flatpak:
    name: '{{ item if item is string else item.name }}'
    remote: "{{ 'flathub' if item is string or item.remote is not defined else item.remote }}"
    state: present
  loop: '{{ linux_desktop_flatpaks }}'

- name: set up flatpak-update timer
  include_role:
    name: systemd_timer
  vars:
    timer_name: flatpak-update
    timer_description: Update flatpaks
    timer_after: network.target
    timer_on_calendar: '{{ linux_desktop_flatpak_update_on_calendar }}'
    timer_exec: flatpak update -y

- name: configure flatpak overrides
  command: flatpak override {{ item.key }} {{ item.value }}
  changed_when: no
  loop: '{{ linux_desktop_flatpak_overrides | dict2items }}'

- import_tasks: freeipa.yml
