- name: create qogir source directories
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ linux_desktop_qogir_source_dir }}'
    - '{{ linux_desktop_qogir_icon_source_dir }}'

- name: extract qogir tarball
  unarchive:
    src: '{{ linux_desktop_qogir_url }}'
    dest: '{{ linux_desktop_qogir_source_dir }}'
    remote_src: yes
    extra_opts:
      - --strip-components=1
  register: linux_desktop_qogir_unarchive

- name: install qogir theme
  command:
    cmd: ./install.sh -d /usr/share/themes -t default
    chdir: '{{ linux_desktop_qogir_source_dir }}'

- name: extract qogir icons tarball
  unarchive:
    src: '{{ linux_desktop_qogir_icon_url }}'
    dest: '{{ linux_desktop_qogir_icon_source_dir }}'
    remote_src: yes
    extra_opts:
      - --strip-components=1
  register: linux_desktop_qogir_icon_unarchive

- name: install qogir icons
  command:
    cmd: ./install.sh -d /usr/share/icons -t default
    chdir: '{{ linux_desktop_qogir_icon_source_dir }}'
