- name: create user
  ipauser:
    ipaadmin_principal: '{{ ipa_user }}'
    ipaadmin_password: '{{ ipa_pass }}'
    name: '{{ ttrss_user }}'
    loginshell: /sbin/nologin
    homedir: '{{ ttrss_home }}'
    givenname: TinyTinyRSS
    sn: Service Account
    state: present
  run_once: yes

- name: retrieve user keytab
  include_role:
    name: freeipa_keytab
  vars:
    keytab_principal: '{{ ttrss_user }}'
    keytab_path: '{{ ttrss_keytab }}'

- name: configure gssproxy for kerberized postgres
  include_role:
    name: gssproxy_client
  vars:
    gssproxy_name: ttrss
    gssproxy_section: service/php-fpm
    gssproxy_client_keytab: '{{ ttrss_keytab }}'
    gssproxy_cred_usage: initiate
    gssproxy_euid: apache

- name: create access group
  ipagroup:
    ipaadmin_principal: '{{ ipa_user }}'
    ipaadmin_password: '{{ ipa_pass }}'
    name: '{{ ttrss_access_group }}'
    nonposix: yes
    state: present
  run_once: yes

- name: create admin group
  ipagroup:
    ipaadmin_principal: '{{ ipa_user }}'
    ipaadmin_password: '{{ ipa_pass }}'
    name: '{{ ttrss_admin_group }}'
    nonposix: yes
    state: present
  run_once: yes
