- name: configure asterisk pbx
  hosts: asterisk_servers
  roles:
    - role: common
      tags: common

    - role: asterisk
      tags: asterisk

    - role: archive_job
      archive_name: asterisk
      archive_user: asterisk
      archive_shell: '{{ asterisk_archive_shell }}'
      tags: archive
