- name: configure vaultwarden
  hosts: bitwarden_servers
  tags: vaultwarden,bitwarden
  roles:
    - role: common
      tags: common

    - role: vaultwarden

    - role: apache_vhost
      apache_default_vhost: yes
      apache_canonical_hostname: '{{ vaultwarden_server_name }}'
      apache_config: '{{ vaultwarden_apache_config }}'
      tags: apache
