- import_playbook: common.yml
  vars:
    hostlist: cups_servers

- name: configure cups
  hosts: cups_servers
  tags: cups
  roles:
    - role: cups_server

    - role: archive_job
      archive_name: cups
      archive_shell: '{{ cups_archive_shell }}'
      tags: archive
