- name: configure cups
  hosts: cups_servers
  roles:
    - role: common
      tags: common

    - role: cups_server
      tags: cups

    - role: archive_job
      archive_name: cups
      archive_shell: '{{ cups_archive_shell }}'
      tags: archive
