- name: apply base configuration
  hosts: freeipa_servers
  roles:
    - role: common
      tags: common

- name: configure freeipa master
  hosts: freeipa_master
  roles:
    - role: freeipa_server
      tags: freeipa

    - role: archive_job
      archive_name: ipa
      archive_on_calendar: 'Sat *-*-* 02:00:00'
      archive_shell: >-
        ipa-backup &&
        find {{ freeipa_backup_dir | quote }} -mindepth 1 -maxdepth 1 -type d
        -exec cp --preserve=timestamps -vr {} . \;
        -exec rm -vrf {} \; &&
        find . -mindepth 1 -type d -exec chmod -v 770 {} +
      tags: archive

- name: configure freeipa replicas
  hosts: freeipa_servers:!freeipa_master
  roles:
    - role: freeipa_server
      tags: freeipa
