- name: apply base configuration
  hosts: freeipa_servers
  roles:
    - role: common
      tags: common

- name: configure freeipa master
  hosts: freeipa_master
  roles:
    - role: freeipa_server
      tags: freeipa

    - role: archive_job
      archive_name: ipa
      archive_on_calendar: 'Sat *-*-* 02:00:00'
      archive_shell: '{{ freeipa_archive_shell }}'
      tags: archive

- name: configure freeipa replicas
  hosts: freeipa_servers:!freeipa_master
  roles:
    - role: freeipa_server
      tags: freeipa
