- name: run common roles
  hosts: rspamd_servers,mail_servers,imap_servers
  tags: common
  roles:
    - common

- name: configure rspamd
  hosts: rspamd_servers
  tags: rspamd
  roles:
    - role: rspamd

    - role: apache_vhost
      apache_default_vhost: yes
      apache_config: '{{ rspamd_apache_config }}'
      tags: apache

    - role: archive_job
      archive_name: rspamd
      archive_shell: '{{ rspamd_archive_shell }}'
      tags: archive

- name: configure postfix
  hosts: mail_servers
  tags: postfix,smtp
  roles:
    - role: postfix_server

- name: configure dovecot
  hosts: imap_servers
  tags: dovecot,imap
  roles:
    - role: dovecot

    - role: archive_job
      archive_name: dovecot
      archive_command: '{{ dovecot_archive_script }}'
      tags: archive
