- name: configure nagios
  hosts: nagios_servers
  roles:
    - role: common
      tags: common

    - role: nagios_server
      tags: nagios

    - role: apache_vhost
      apache_default_vhost: yes
      apache_document_root: '{{ nagios_html_dir }}'
      apache_config: '{{ nagios_apache_config }}'
      tags: apache
