- name: configure tinytinyrss
  hosts: ttrss_servers
  roles:
    - role: common
      tags: common

    - role: ttrss
      tags: ttrss

    - role: php
      php_fpm_environment: '{{ ttrss_php_environment }}'
      tags: php

    - role: apache_vhost
      apache_default_vhost: yes
      apache_canonical_hostname: '{{ ttrss_server_name }}'
      apache_document_root: '{{ ttrss_home }}'
      apache_config: '{{ ttrss_apache_config }}'
      tags: apache
