- name: configure unifi controller
  hosts: unifi_controllers
  tags: unifi
  roles:
    - role: common
      tags: common

    - role: unifi

    - role: archive_job
      archive_name: unifi
      archive_shell: '{{ unifi_archive_shell }}'
      tags: archive
