- name: configure mediawiki
  hosts: wiki_servers
  roles:
    - role: common
      tags: common

    - role: mediawiki
      tags: wiki,mediawiki

    - role: apache_vhost
      apache_default_vhost: yes
      apache_document_root: '{{ mediawiki_home }}'
      apache_config: '{{ mediawiki_apache_config }}'
      tags: apache

    - role: php
      php_fpm_environment: '{{ mediawiki_php_environment }}'
      php_fpm_admin_values: '{{ mediawiki_php_admin_values }}'
      tags: php

    - role: archive_job
      archive_name: mediawiki
      archive_shell: '{{ mediawiki_archive_shell }}'
      tags: archive
