- name: configure yum mirrors
  hosts: yum_mirrors
  roles:
    - role: common
      tags: common

    - role: yum_mirror
      tags: yum

    - role: apache_vhost
      apache_default_vhost: yes
      apache_document_root: '{{ yum_mirror_webroot }}'
      apache_autoindex: yes
      apache_redirect_to_https: no
      tags: apache

- name: configure local package repository
  hosts: yum_mirrors
  roles:
    - role: yum_disable_default_repos
      tags: yum

    - role: yum
      yum_repositories:
        - rocky-baseos
        - rocky-appstream
        - rocky-extras
        - epel
      tags: yum

    # nagios_client has to run *after* EPEL repository has been configured.
    - role: nagios_client
      tags: nagios
