- name: configure znc
  hosts: znc_servers
  roles:
    - role: common
      tags: common

    - role: znc
      tags: znc

    - role: archive_job
      archive_name: znc
      archive_shell: '{{ znc_archive_shell }}'
      tags: archive
