- name: check if /etc/lvm exists
  stat:
    path: /etc/lvm
  register: lvm_conf_directory

- name: set use_devicesfile option
  template:
    src: etc/lvm/lvm.conf.j2
    dest: /etc/lvm/lvm.conf
  when: lvm_conf_directory.stat.exists
