- name: install packages
  dnf:
    name: '{{ coturn_packages }}'
    state: present

- name: generate coturn configuration
  template:
    src: etc/coturn/turnserver.conf.j2
    dest: /etc/coturn/turnserver.conf
    owner: root
    group: coturn
    mode: 0640
  notify: restart coturn

- name: open firewall ports
  firewalld:
    port: '{{ item }}'
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - '{{ coturn_port }}/tcp'
    - '{{ coturn_port }}/udp'
    - '{{ coturn_min_port }}-{{ coturn_max_port }}/udp'
  tags: firewalld

- name: create systemd override directory
  file:
    path: /etc/systemd/system/coturn.service.d
    state: directory

- name: create systemd override file
  copy:
    src: etc/systemd/system/coturn.service.d/override.conf
    dest: /etc/systemd/system/coturn.service.d/override.conf
  register: coturn_systemd_unit
  notify: restart coturn

- name: reload systemd units
  systemd:
    daemon_reload: yes
  when: coturn_systemd_unit.changed

- name: enable coturn
  systemd:
    name: coturn
    enabled: yes
    state: started
